updated +getDeviceInfo

diff --git a/+/+releaseHal b/+/+releaseHal
--- a/+/+releaseHal
+++ b/+/+releaseHal
@@ -1,9 +1,25 @@
 
 
+cd $(git rev-parse --show-toplevel)
+cd cc-hal
+cargo bitbake
+mv cc-hal_0.1.0.bb ../../../YOCTO/firmware_yocto/meta-cc/recipes-cc/cc-hal/
 
-cd /home/thor/workspace/firmware_hal/cc-hal
-~/installers/cargo-bitbake bitbake
-mv cc-hal_0.1.0.bb /home/thor/workspace/firmware_yocto/meta-cc/recipes-cc/cc-hal
+# Save the branch name from the source repository
+src_branch=$(git rev-parse --abbrev-ref HEAD)
+
+cd ../../../YOCTO/firmware_yocto/meta-cc/recipes-cc/cc-hal/
+
+# Check the branch name from the destination repository
+dst_branch=$(git rev-parse --abbrev-ref HEAD)
+
+if [ "$src_branch" != "$dst_branch" ]; then
+  echo "Branches are not the same. Aborting."
+  exit 1
+else 
+  echo "Updating branch $dst_branch"
+fi
+
 git commit -m "meta-cc: cc-hal: bump srcrev" cc-hal_0.1.0.bb
-cd /home/thor/workspace/firmware_yocto/meta-cc/recipes-cc/cc-hal
-echo "Rlease created!"
+git push
+echo "Release created!"
